// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vezeeta.DBL;

#nullable disable

namespace vezeeta.DBL.Migrations
{
    [DbContext(typeof(VezeetaDB))]
    [Migration("20230131221355_speciality_entity")]
    partial class specialityentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CenterSpeciality", b =>
                {
                    b.Property<Guid>("CentersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecialitiesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CentersId", "SpecialitiesId");

                    b.HasIndex("SpecialitiesId");

                    b.ToTable("CenterSpeciality");
                });

            modelBuilder.Entity("vezeeta.DBL.Center", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Owner Doctor UserId Where User Is Doctor");

                    b.Property<float?>("amount")
                        .HasColumnType("real");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2")
                        .HasComment("Created At DateTime");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name_en")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slug_ar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slug_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasComment("Last Update DateTime");

                    b.Property<int>("views")
                        .HasColumnType("int");

                    b.Property<int>("visitors")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("name_ar")
                        .IsUnique();

                    b.HasIndex("name_en")
                        .IsUnique();

                    b.ToTable("centers");
                });

            modelBuilder.Entity("vezeeta.DBL.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2")
                        .HasComment("Created At DateTime");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name_ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name_en")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("slug_ar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slug_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasComment("Last Update DateTime");

                    b.HasKey("Id");

                    b.HasIndex("name_ar")
                        .IsUnique();

                    b.HasIndex("name_en")
                        .IsUnique();

                    b.ToTable("departments");
                });

            modelBuilder.Entity("vezeeta.DBL.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("N_ID")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Doctor User National ID");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2")
                        .HasComment("Created At DateTime");

                    b.Property<DateTime?>("dob")
                        .HasColumnType("datetime2")
                        .HasComment("User Date Of Barth");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("is_admin")
                        .HasColumnType("bit");

                    b.Property<bool>("is_doctor")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasComment("Last Update DateTime");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("username")
                        .IsUnique()
                        .HasFilter("[username] IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("vezeeta.DBL.db.Models.CenterSpeciality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpecialityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("centersSpecialities");
                });

            modelBuilder.Entity("vezeeta.DBL.db.Models.Speciality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MainSpecialityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2")
                        .HasComment("Created At DateTime");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name_en")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("slug_ar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slug_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasComment("Last Update DateTime");

                    b.HasKey("Id");

                    b.HasIndex("MainSpecialityId");

                    b.HasIndex("name_ar")
                        .IsUnique();

                    b.HasIndex("name_en")
                        .IsUnique();

                    b.ToTable("specialities");
                });

            modelBuilder.Entity("CenterSpeciality", b =>
                {
                    b.HasOne("vezeeta.DBL.Center", null)
                        .WithMany()
                        .HasForeignKey("CentersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vezeeta.DBL.db.Models.Speciality", null)
                        .WithMany()
                        .HasForeignKey("SpecialitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vezeeta.DBL.Center", b =>
                {
                    b.HasOne("vezeeta.DBL.Department", "Department")
                        .WithMany("Centers")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("vezeeta.DBL.User", "User")
                        .WithMany("Centers")
                        .HasForeignKey("UserId");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vezeeta.DBL.db.Models.CenterSpeciality", b =>
                {
                    b.HasOne("vezeeta.DBL.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId");

                    b.HasOne("vezeeta.DBL.db.Models.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityId");

                    b.Navigation("Center");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("vezeeta.DBL.db.Models.Speciality", b =>
                {
                    b.HasOne("vezeeta.DBL.db.Models.Speciality", "MainSpeciality")
                        .WithMany()
                        .HasForeignKey("MainSpecialityId");

                    b.Navigation("MainSpeciality");
                });

            modelBuilder.Entity("vezeeta.DBL.Department", b =>
                {
                    b.Navigation("Centers");
                });

            modelBuilder.Entity("vezeeta.DBL.User", b =>
                {
                    b.Navigation("Centers");
                });
#pragma warning restore 612, 618
        }
    }
}
